### ISSUE TITLE
Import styles in development mode do not take effect

### ISSUE THREAD

**Issue by OSpoon** [extension-js/extension.js#105]
@cezaraugusto，Sorry, it seems that importing css does not work in development mode at the moment, We still need to make a few changes.

* invalid template：`newtab`

**Comment by cezaraugusto** [comment]
@OSpoon can't repro in the main branch. still happening?

**Comment by OSpoon** [comment]
Maybe due to caching, I will close this issue first.

**Comment by OSpoon** [comment]
Need to make sure again !!!

### Steps
1. switch to the main branch；
2. create the newtab project: `yarn extension create ../react-ext --template=react`

### Now ❓
1. Template file for identification？
![image](https://github.com/extension-js/extension.js/assets/10126623/79569656-faab-4bca-bb1c-dcc6f59e9dcb)

2. The development pattern is missing？

Run `yarn dev`:

![image](https://github.com/extension-js/extension.js/assets/10126623/8b8dbe61-802c-4fac-a911-16416e13d07c)

![image](https://github.com/extension-js/extension.js/assets/10126623/dd55460b-8ca3-43a0-871f-407a4c6d4c06)

Run `yarn start`:

![image](https://github.com/extension-js/extension.js/assets/10126623/1d1520ee-51ff-464f-8ccb-a5dc1b683acf)

![image](https://github.com/extension-js/extension.js/assets/10126623/944d91ec-040a-49bf-8983-86996e966c61)
