### ISSUE TITLE
Is there a method to avoid style lack?

### ISSUE THREAD

**Issue by dinfer** [extension-js/extension.js#118]
Tailwind resets all the styles in the pages which my content script inject into. I just use the official react-typescript template, and I only change the `content_scripts.matches` to `["<all_urls>"]` in the `manifest.json`, no code is modified.

Is there a way to avoid the "style lack"? It seems WebComponent cannot be used here, cause `customElements` is `null` in the isolated runtime of content script. 

<img width="1200" alt="image" src="https://github.com/extension-js/extension.js/assets/11496403/91179c95-8794-4bf3-80eb-09328569e3b7">

**Comment by cezaraugusto** [comment]
hi @dinfer not sure what is the question. I guess you want to prevent Tailwind from injecting default styles into the page?

**Comment by dinfer** [comment]
@cezaraugusto I want to use tailwind for the elements created by content script, but I dont want to affect the page content styles.

For example, I want to use tailwind to style the panel at right-bottom, but the links of google should remain be blue.

I need a way to make tailwind only affect the elements created by content script

**Comment by cezaraugusto** [comment]
sure, please take a look at my reply in https://github.com/extension-js/extension.js/issues/48#issuecomment-2089148686, I guess adding the content element to the shadow dom will do the trick

**Comment by dinfer** [comment]
@cezaraugusto Thanks, I'm closing this issue
