### ISSUE TITLE
css module and less are not supported

### ISSUE THREAD

**Issue by baishiup** [extension-js/extension.js#124]
1 css module and less are not supported
2 style file was introduced in the component, which takes effect at dev but not after build

**Comment by cezaraugusto** [comment]
Thanks for reporting! Will take a look

**Comment by cezaraugusto** [comment]
hey @baishiup it works now, please try one of the following:

```sh
# css module
npx extension@latest create my-extension --template=css-module
```

```sh
# less
npx extension@latest create my-extension --template=less
```

```sh
# less
npx extension@latest create my-extension --template=less-module
```

**Comment by cezaraugusto** [comment]
closing as completed. pleae re-open if I'm mistaken
