### ISSUE TITLE
path resolve with empty string

### ISSUE THREAD

**Issue by bugficks** [extension-js/extension.js#125]
hi,

`chrome.runtime.getURL('')` throws an 'unable to resolve the path' error, this is a valid path though.
Also I guess URL may contain parameters as well.

the workaround is:
`chrome.runtime.getURL('public/dummy').replace('public/dummy', '');
`
which is kinda ugly :)

**Comment by cezaraugusto** [comment]
Thanks for reporting, working on a fix

**Comment by cezaraugusto** [comment]
fixed in extension@2.0.0-alpha.29. please reopen if I'm mistaken
