### ISSUE TITLE
Add react-svgr lib support

### ISSUE THREAD

**Issue by wjureczka** [extension-js/extension.js#126]
Hi there! Thank you for your hard work on the library! It's great. I have a question about eject option. Is it possible?

**Comment by cezaraugusto** [comment]
hi @wjureczka! I do plan to support some sort of configuration file. What would be the reason for the eject? Do you miss some plugin or something? Curious to know the use case

**Comment by wjureczka** [comment]
@cezaraugusto I have one example https://react-svgr.com/. I would like to inject it to webpack process. WDYT?

**Comment by cezaraugusto** [comment]
hi @wjureczka, sounds valid :) I'm cooking a big release, will add it in

**Comment by cezaraugusto** [comment]
Completed in [e462c4f](https://github.com/extension-js/extension.js/commit/e462c4f9ca76adf2baf9c2ad0ac3f7aa55f872de). cc @wjureczka you can bootstrap a new extension with built-in svgr support via

```sh
pnpx extension@latest create your-extension-name --template=content-react-svgr
```

let me know how it goes when you get a chance!

**Comment by cezaraugusto** [comment]
closing as completed. feel free to circle back on this if something is odd. thanks!
