### ISSUE TITLE
tailwind.config.js configuration is not being applied to the Extension being built

### ISSUE THREAD

**Issue by elg0nz** [extension-js/extension.js#130]
I've encountered an issue with the `tailwind.config.js` file not applying changes as expected during the build process of my extension. Specifically, I added a prefix configuration to the `tailwind.config.js` file, but the generated CSS code does not include the specified prefix.

## Steps to Reproduce

0. Create a new extension with the `npx extension@latest create my-extension --template=react-typescript` or clone https://github.com/elg0nz/extension-js-tailwind-config-bug-sample-app/tree/main
1. Add a prefix configuration in the `tailwind.config.js` file:
   ```js
   // tailwind.config.js
   module.exports = {
     prefix: 'xw-',
     // other configurations...
   }
   ```
2. Build the extension via `npm run build`
3. Inspect the generated CSS inside the content-0.js to verify if the prefix is applied.

## Expected Behavior

The generated CSS should include the specified prefix (`xw-`) for all Tailwind utility classes.

## Actual Behavior

The generated CSS does not include the specified prefix, indicating that the changes in the `tailwind.config.js` file are not being applied.

See snippet below:
```js
--tw-shadow-colored: 0 0 #0000;\n  --tw-blur:  ;\n  --tw-brightness:  ;\n  --tw-contrast:  ;\n  --tw-grayscale:  ;\n  --tw-hue-rotate:  ;\n  --tw-invert:  ;\n  --tw-saturate:  ;\n  --tw-sepia:  ;\n  --tw-drop-shadow:  ;\n  --tw-backdrop-blur:  ;\n  --tw-backdrop-brightness:  ;\n  --tw-backdrop-contrast:  ;\n  --tw-backdrop-grayscale:  ;\n  --tw-backdrop-hue-rotate:  ;\n  --tw-backdrop-invert:  ;\n  --tw-backdrop-opacity:  ;\n  --tw-backdrop-saturate:  ;\n  --tw-backd
```

### Additional Information

- Tailwind CSS version: 3.4.4
- Build tool: npm
- Operating System: macOS Sonoma 14.5

### Attachments

https://github.com/elg0nz/extension-js-tailwind-config-bug-sample-app/tree/main

Please let me know if any additional information is required or if there are any troubleshooting steps I can follow to resolve this issue.

**Comment by cezaraugusto** [comment]
hi @elg0nz, thanks for reporting! Taking a look

**Comment by cezaraugusto** [comment]
I managed to use a custom prefix + CSS variables just fine, pls let me know if I misunderstand the issue. Below is a fork of your repo.

Repo: https://github.com/cezaraugusto/extension-js-tailwind-prefix-css-variable


<details>
<summary>
Relevant Code 
</summary>

```js
// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: "xw-",
  content: ["**/*.html", "**/*.tsx"],
  theme: {
    extend: {
      colors: {
        myCustomColor: "var(--my-custom-color)",
      },
    },
  },
  plugins: [],
};
```

```css
// content/base.css

:root {
  --my-custom-color: slategray;
}

@tailwind base;
@tailwind components;
@tailwind utilities;
```

```tsx
// content/ContentApp.tsx
export default function ContentApp() {
  return (
    <div className="xw-bg-myCustomColor xw-flex xw-items-center xw-justify-center xw-min-h-screen">
      <h1 className="xw-text-2xl xw-p-4 xw-bg-myCustomColor">
        Hello, Tailwind with "xw" prefix and CSS Variable!
      </h1>
    </div>
  );
}

```

</details>
## Preview 
<img width="1200" alt="Screenshot 2024-07-11 at 18 26 08" src="https://github.com/user-attachments/assets/a9817574-512b-4406-b7c2-5b5a571df0b3">

**Comment by elg0nz** [comment]
@cezaraugusto nice, so it was just missing adding `babel-plugin-transform-import-css` to the repo?

**Comment by cezaraugusto** [comment]
@elg0nz that's not needed actually, added to the commit while testing by accident. It's written as "conzfig" so Extension.js doesn't catch it :D [babel.conzfig.json](https://github.com/cezaraugusto/extension-js-tailwind-prefix-css-variable/commit/a0f711eee08d04f9ce64e1e61e296c5722cfd575#diff-662dbb05718ba73ee777b4708937d68e6b5e12773a683e40aaa574da23914ce6). The changes above should do the trick

**Comment by elg0nz** [comment]
Looks like I just needed to actually use the prefixed rules in order for tailwindcss to see them. Closing!
