### ISSUE TITLE
manifest 'background' processing bug?

### ISSUE THREAD

**Issue by bugficks** [extension-js/extension.js#132]
given:
```
  "background": {
    "service_worker": "./background.ts",
    "background": {
      "scripts": [
        "background.ts"
      ]
    }
  },
```
results in (notice the unprocessed **`background.ts`**):
```
  "background": {
    "service_worker": "background/service_worker.js",
    "background": {
      "scripts": [
        "background.ts"
      ]
    }
  },
```

recent browser versions are able to deal with this. 
I guess another question is to use the same .ts or allow a different one, in case of possible differences.

[Browser support](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support)

Support for the scripts, page, and service_worker properties varies between browsers like this:
 
- Chrome:
        supports background.service_worker.
        supports background.scripts (and background.page) in Manifest V2 extensions only.
        before Chrome 121, Chrome refuses to load a Manifest V3 extension with background.scripts or background.page present. From Chrome 121, their presence in a Manifest V3 extension is ignored.
- Firefox:
        background.service_worker is not supported (see [Firefox bug 1573659](https://bugzilla.mozilla.org/show_bug.cgi?id=1573659)).
        supports background.scripts (or background.page) if service_worker is not specified or the service worker feature is disabled. Before Firefox 120, Firefox did not start the background page if service_worker was present (see [Firefox bug 1860304](https://bugzil.la/1860304)). From Firefox 121, the background page starts as expected, regardless of the presence of service_worker.
- Safari:
        supports background.service_worker.
        supports background.scripts (or background.page) if service_worker is not specified.

**Comment by cezaraugusto** [comment]
we support non-standard cross-browser manifest fields (not released), made by a great contribution here: https://github.com/extension-js/extension.js/pull/128. It allows you to add a browser prefix to manifest fields, like:

```json5
{
  background: {
    firefox:scripts: [...], // applied only to Firefox
    service_worker: 'sw.js' // applied only to Chrome
}
```

this way you can work on multiple browsers at once and ensure compatibility

**Comment by bugficks** [comment]
not sure what I am doing wrong but if I add to source manifest:
```
    "background": {
        "chromium:service_worker": "background.ts",
        "firefox:scripts": [
            "background.ts"
        ]
    },
```
after running build this ends up in dist/chrome/manifest.json
```
  "background": {
    "chromium:service_worker": "background.ts",
    "firefox:scripts": [
      "background.ts"
    ]
  },
```
which is even worse :)

my workaround is:
```
  "background": {
    "service_worker": "background.ts",
    "background": {
      "scripts": [
        "background/service_worker.js"
      ]
    }
  },
```
which produces the manifest I want :)

**Comment by cezaraugusto** [comment]
@bugficks yeah it's not released yet, there are a few issues with current implementation. Will land in the next release once #137 is out

**Comment by cezaraugusto** [comment]
below you can pull a template that works on both Chromium-based browsers and Firefox using the snipped above.

```
npx extension create my-extension --template=content-typescript
```

closing as completed, please ping if I'm wrong.
