### ISSUE TITLE
Outdated links on CSS Modules doc page

### ISSUE THREAD

**Issue by amal** [extension-js/extension.js#133]
The links at the bottom of this page are out of date:
https://extension.js.org/n/development/modern-css/css-modules/

PostCSS leads to empty page and other three lead to 404.

**Comment by cezaraugusto** [comment]
hi @amal! thanks for reporting.

I'm currently fixing a few outstanding bugs. Do you mind pushing a PR to remove the links for now? repo is https://github.com/extension-js/extension.js.org. Would really appreciate it

**Comment by amal** [comment]
@cezaraugusto, here is the PR: https://github.com/extension-js/extension.js.org/pull/3

Please tell if anything needs to be changed or added.

**Comment by cezaraugusto** [comment]
hi @amal just approved, thanks!
