### ISSUE TITLE
Catching the errors from the web browser

### ISSUE THREAD

**Issue by AthulKKDev** [extension-js/extension.js#136]
![Screenshot 2024-07-20 150303](https://github.com/user-attachments/assets/f8cd2ac3-377a-4dab-a725-f1721db4e501)
![Screenshot 2024-07-20 150222](https://github.com/user-attachments/assets/379c4794-6694-4a29-a9a2-4f6099fcd294)
I am experiencing a problem with a Chrome extension I developed using the [extension.js](https://github.com/extension-js/extension.js) library. The issue I am facing involves the extension capturing errors generated by the browser and causing the website to crash. Is there a solution available to address this issue?

**Comment by cezaraugusto** [comment]
hi @AthulKKDev, can you try updating to the latest version? Currently `2.0.0-alpha.26`.

If that doesn't work, please share the steps you took that raised the issue so I can try reproducing. Thanks!

**Comment by cezaraugusto** [comment]
hi @AthulKKDev I'm cleaning up the house, will close this one as not actionable for now. if you still face it please re-open with some steps I can reproduce the bug. thanks!
