### ISSUE TITLE
Support configuration file for custom plugins

### ISSUE THREAD

**Issue by 0xBigBoss** [extension-js/extension.js#142]
First off, thank you so much for the amazing repo. It's helped me so much already today bootstrap my idea quickly. However, I am wondering how I could potentially include some custom webpack plugins so I could easily use a react native (web) setup.

I'd love to use my favorite UI library, https://tamagui.dev, but I don't see an easy way to do that currently unless I do something like this, https://github.com/extension-js/extension.js/commit/516381a3b183c2596c49385ce8a40c6306f24674.

Wondering if something like this is coming soon or if there's something I could potentially help with adding this eject feature.

> I do plan to support some sort of configuration file. What would be the reason for the eject? Do you miss some plugin or something? Curious to know the use case

https://github.com/extension-js/extension.js/issues/126#issuecomment-2218956669

**Comment by cezaraugusto** [comment]
hi @0xBigBoss! thanks for the kind words and for the feedback. 

I'm not against an eject option but that would be much harder to do than creating a config file that exposes the webpack config. After #137 this is definitely a priority.

**Comment by 0xBigBoss** [comment]
Hi @cezaraugusto I think what you are suggesting for the config file is great and would work perfectly. I think I would rather not have to eject from this awesome setup you have here.

**Comment by cezaraugusto** [comment]
hey @0xBigBoss the config file is a thing now! use `extension.config.js` and add the webpack plugins you want. see the "crypto" template for reference: 

```
npx extension@latest create my-extension --template=new-crypto
```

let me know how it goes!

**Comment by cezaraugusto** [comment]
closing as completed. please open a new one if I missed something
