### ISSUE TITLE
Support for installing and using npm packages in extensions

### ISSUE THREAD

**Issue by FXT-SYSTEM** [extension-js/extension.js#143]
I am a developer who has just come across this wonderful library package today. I am wondering if, while developing my extension with it, I can install other packages through a package manager like npm and require those packages in the source code of my extension to use them.

**Comment by cezaraugusto** [comment]
hello @FXT-SYSTEM! thanks for the kind words.

yes, totally possible! just use your existing package.json for that. If you want a template with pre-built solutions, you can try running `extension create your-extension-name --template=<your_template_name>`. You can see a list of them at https://extension.js.org/n/getting-started/templates/. Let me know if you need a hand!

**Comment by cezaraugusto** [comment]
Closing as not actionable. Feel free to create a new issue it there is something else you want to ask/report. Thanks!
