### ISSUE TITLE
Add `dist` and other ignores to `.gitignore` during `create`

### ISSUE THREAD

**Issue by karlhorky** [extension-js/extension.js#148]
During scaffolding with `extension@latest create`, it would be great to:

1. Create a `.gitignore` (if one does not exist)
2. Add a line for each path which should be ignored (only if the lines are not already present, similar to https://github.com/microsoft/create-playwright/pull/122)

This is similar to what @jmg-duarte suggested:

- https://github.com/extension-js/extension.js/issues/54#issuecomment-2107893659

But the PR closing issue #54 did not include `.gitignore` support:

- https://github.com/extension-js/extension.js/pull/121

Some ideas for paths that could be ignored:

- `dist`
- `extension.d.ts` (as per [the TypeScript docs](https://extension.js.org/n/development/modern-javascript/typescript/#:~:text=Ensure%20the%20extension.d.ts%20file%20is%20added%20to%20your%20.gitignore%20file%20as%20it%20is%20auto%2Dgenerated%20and%20only%20useful%20during%20development%20mode.))

**Comment by jmg-duarte** [comment]
You should be able to just write the `.gitignore` in this line — https://github.com/extension-js/extension.js/pull/121/files#diff-c79a9d3ab27d3a96709ef6bb93d65fe51be0b7fde2d7f60d5821d2e15f2173aeR64

Something like
```ts
fs.writeFile(".gitignore", gitignoreContents, (err) => { /* TODO: error handling */ })
```

As for the contents, without interaction I'd just cherry pick them from https://github.com/github/gitignore/blob/main/Node.gitignore

And add other paths that might be relevant

**Comment by cezaraugusto** [comment]
hi folks, thanks for the feedback!

there is a PR open for this request in #158, feel free to review/suggest changes!
