### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by OSpoon** [extension-js/extension.js#168]
The path for the template cannot be found in development mode.

```
➜  extension.js git:(content-css-options) ✗ nr extension create ../content-less-ext --template content-less

> extension@ extension /Users/xinzhang/Documents/GitHub/extension.js
> dotenv -- ts-node ./programs/cli/dist/cli.js "create" "../content-less-ext" "--template" "content-less"

🐣 - Starting a new browser extension named content-less-ext...
🤝 - Ensuring content-less-ext folder exists...
🤞 - Checking if destination path is writeable...
🔎 - Scanning for potential conflicting files...
🧰 - Installing content-less-ext from template content-less...
✖︎✖︎✖︎ Can't find template content-less for content-less-ext:
Error: ENOENT: no such file or directory, lstat '/Users/xinzhang/Documents/GitHub/extension.js/node_modules/.pnpm/extension-create@2.0.0-alpha.23/examples/content-less'
    at async lstat (node:internal/fs/promises:1021:18)
    at async Promise.all (index 0)
    at async checkPaths (node:internal/fs/cp/cp:76:39)
    at async cpFn (node:internal/fs/cp/cp:65:17)
    at async Fe (/Users/xinzhang/Documents/GitHub/extension.js/node_modules/.pnpm/extension-create@2.0.0-alpha.23/node_modules/extension-create/dist/module.js:28:2138)
    at async ln (/Users/xinzhang/Documents/GitHub/extension.js/node_modules/.pnpm/extension-create@2.0.0-alpha.23/node_modules/extension-create/dist/module.js:38:771)
    at async Command.<anonymous> (/Users/xinzhang/Documents/GitHub/extension.js/programs/cli/dist/cli.js:197:3) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/xinzhang/Documents/GitHub/extension.js/node_modules/.pnpm/extension-create@2.0.0-alpha.23/examples/content-less'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by cezaraugusto** [comment]
oh noes that's bad :_(

just released beta@24, might giving it a go?

```
pnpm extension@latest create ../content-less-ext --template content-less
```

<img width="553" alt="Screenshot 2024-09-06 at 11 29 50" src="https://github.com/user-attachments/assets/f379d1ad-4d79-414c-85a8-8a32976d461e">

**Comment by OSpoon** [comment]
> oh noes that's bad :_(
> 
> just released alpha@24, might giving it a go?
> 
> ```
> pnpm extension@latest create ../content-less-ext --template content-less
> ```
> 
> <img alt="Screenshot 2024-09-06 at 11 29 50" width="553" src="https://private-user-images.githubusercontent.com/4672033/365201961-f379d1ad-4d79-414c-85a8-8a32976d461e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzMzODcsIm5iZiI6MTcyNTYzMzA4NywicGF0aCI6Ii80NjcyMDMzLzM2NTIwMTk2MS1mMzc5ZDFhZC00ZDc5LTQxNGMtODVhOC04YTMyOTc2ZDQ2MWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMTQzMTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDYyNTA1OWQ5ZTY1ODNiODc4NzFhN2FhMzFiYjgwZGU4ODI1NGVhODA5NzExMjBmMjc3NGY2MDdmM2MzOGIyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vNdtfrip7Y3FGBijlXMWUctKIdhUql2wNWrMuMGv36c">

Path issues only occur in development mode, I need to use the local template.

**Comment by cezaraugusto** [comment]
cant repro as well 😢 

<img width="702" alt="Screenshot 2024-09-06 at 13 18 52" src="https://github.com/user-attachments/assets/e80d9958-7a3c-4d6c-b8fc-2fe8af35c0e9">

**Comment by cezaraugusto** [comment]
I did found an issue with the symlink if `EXTENSION_ENV=development` is set. not sure if related

<img width="865" alt="Screenshot 2024-09-06 at 13 23 14" src="https://github.com/user-attachments/assets/07739e52-4e3c-44bc-b90c-94dd97707bb0">

**Comment by OSpoon** [comment]
> I did found an issue with the symlink if `EXTENSION_ENV=development` is set. not sure if related如果设置了`EXTENSION_ENV=development` ，我确实发现了符号链接的问题。不确定是否相关
> 
> <img alt="Screenshot 2024-09-06 at 13 23 14" width="865" src="https://private-user-images.githubusercontent.com/4672033/365238848-07739e52-4e3c-44bc-b90c-94dd97707bb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDI2NDQsIm5iZiI6MTcyNTY0MjM0NCwicGF0aCI6Ii80NjcyMDMzLzM2NTIzODg0OC0wNzczOWU1Mi00ZTNjLTQ0YmMtYjkwYy05NGRkOTc3MDdiYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMTcwNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBlY2I0MzU2NWJmZWE2ZjliOTQzOTUwZGJhY2ExMTUwOWEwNWU1ZGMyMWE2MWZlNTFiY2RkNjNmYzMyZWIzNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NFcMf-kULKi9WBUj609BG6EP_BdmAE9K7k9E2-5nvPg">

Need to handle the symlink issue first, then we can determine if the code runs correctly.
```typescript
// programs/create/steps/import-external-template.ts

if (process.env.EXTENSION_ENV === 'development') {
  console.log(messages.installingFromTemplate(projectName, template))

  templatePath = path.join(projectPath, templateName)

  await fs.cp(
    path.join(__dirname, '..', '..', '..', 'examples', templateName),
    templatePath,
    {recursive: true}
  )
}
```

**Comment by dshook** [comment]
Just ran into this as well, latest doesn't work for me either:

```
npx extension@latest create test-extension --template=react-typescript

Need to install the following packages:
extension@2.0.0-alpha.26
Ok to proceed? (y) y
🐣 - Starting a new browser extension named cat-search...
🤝 - Ensuring cat-search folder exists...
🤞 - Checking if destination path is writeable...
🔎 - Scanning for potential conflicting files...
🧰 - Installing cat-search from template react-typescript...
Removing existing .go-git-it-temp-folder...
[=                                                 ] 2% 18.5sError pulling git repository: [Error: ENOENT: no such file or directory, rename 'examples/react-typescript' -> '/Users/dillonshook/react-typescript'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: 'examples/react-typescript',
  dest: '/Users/dillonshook/react-typescript'
}
```

**Comment by OSpoon** [comment]
After running `cleanInstall`, I re-ran the previous create command, and found that there was no issue, which seems to be caused by caching.

**Comment by cezaraugusto** [comment]
thanks @OSpoon!

@dshook I made a few changes to the template names, please check https://extension.js.org/docs/getting-started/templates for the new template naming. I'm going to close this one for now, please re-open if there's an issue. Thanks!
