### ISSUE TITLE
Error: spawn pnpm ENOENT

### ISSUE THREAD

**Issue by OSpoon** [extension-js/extension.js#170]
Error messages that appear in development mode.

```
➜  extension.js git:(content-css-options) nr extension create ../init-ext --template init

> extension@ extension /Users/xinzhang/Documents/GitHub/extension.js
> dotenv -- ts-node ./programs/cli/dist/cli.js "create" "../init-ext" "--template" "init"

🐣 - Starting a new browser extension named init-ext...
🤝 - Ensuring init-ext folder exists...
🤞 - Checking if destination path is writeable...
🔎 - Scanning for potential conflicting files...
🧰 - Installing init-ext...
📝 - Writing package.json metadata...
🛠  - Installing dependencies... (takes a moment)
Error: spawn pnpm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn pnpm',
  path: 'pnpm',
  spawnargs: [ 'link' ]
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by OSpoon** [comment]
> that's bad. now I'm wondering how long `create` was broken.那很糟糕。现在我想知道`create`被破坏了多长时间。
> 
> seems ok after alpha@24, let me know if not.alpha@24 之后似乎没问题，如果不行请告诉我。
> 
> <img alt="Screenshot 2024-09-06 at 11 34 25" width="542" src="https://private-user-images.githubusercontent.com/4672033/365203422-0ec886f4-3850-4a7d-abe3-aaece2ce1544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MzM3OTUsIm5iZiI6MTcyNTYzMzQ5NSwicGF0aCI6Ii80NjcyMDMzLzM2NTIwMzQyMi0wZWM4ODZmNC0zODUwLTRhN2QtYWJlMy1hYWVjZTJjZTE1NDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDZUMTQzODE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMzMWNjZTk5ODMyZGUzY2QwZDdlY2IxZjM3Mzc0Yjk1MjBiYTdkMzc3ZDY0M2I3YzY1ZTFiZDM2YTkzZTIxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Twsmm1w9PrlxDUhG9WjkSxxxFh6AEnGe2PoEUFrhae0">

The function seems to be executing with some issues in development mode.
```
if (process.env.EXTENSION_ENV === 'development') {
  await createSymlink(projectPath)
}
```

**Comment by cezaraugusto** [comment]
I'll remove it
