### ISSUE TITLE
How can I properly use an existing Chrome profile?

### ISSUE THREAD

**Issue by karaggeorge** [extension-js/extension.js#176]
I have a development profile for Chrome, which is under:
`/Users/{username}/Library/Application Support/Google/Chrome/Profile 1`

I pass that to `-u` for the CLI, but it always creates a new profile. I've tried many variations but I can't load an existing profile no matter what I do

Using `2.0.0-alpha.26`, but I tried `1.8.0` and had the same issue there as well

**Comment by karaggeorge** [comment]
I think this fixes the issue: https://github.com/extension-js/extension.js/pull/179

**Comment by karaggeorge** [comment]
I do still have to completely close my Chrome instance before I run the comment, otherwise it won't install the extensions.

Also, it does clear all my local data when I do that, and I have to sign in to everything again when I open it the next time
Not sure if there's a better way to do that. Maybe an option to not pass [these](https://github.com/karaggeorge/extension.js/blob/4ec1e9263f653db8aeeef97e45f264fad40c2b31/programs/develop/plugin-browsers/run-chromium/browser-config.ts#L23-L81) flags if you're using your personal profile?

**Comment by cezaraugusto** [comment]
@karaggeorge I'm not sure I'm following https://github.com/extension-js/extension.js/issues/176#issuecomment-2346880050, could you describe more fully? In terms of a better developer experience, what is the expected behavior?

About the default flags, I'd accept a PR that adds the flgas only if you do not explicitly set the profile

**Comment by karaggeorge** [comment]
My ideal flow is that I pass my chrome profile, so I can use that when testing the extension (with my existing sessions/cookies etc)

It looks like if you want to use `--load-extension` and have it work, you need to first close that profile/Chrome completely, otherwise it just opens a tab but doesn't install them

When I do that, it works as expected (as in installs the extensions), but it also clears all my site data (cookies/storage). I'd like to avoid that. I'm assuming that has to do with the rest of the flags, but I'm not 100% sure

I'll open a PR that does not pass the flags if a profile is passed and see if that works

**Comment by cezaraugusto** [comment]
@karaggeorge thanks. feel free to open another issue so we can discuss it further
