### ISSUE TITLE
Include a polyfill for `crypto-browserify`

### ISSUE THREAD

**Issue by aeddi** [extension-js/extension.js#180]
Hello, 
thanks for this really handy and well-documented tool!  

I started writing an extension based on the `action-chatgpt` template (so it’s set up with TypeScript and React). I’m having an issue when I try to include a package that imports the `crypto` library. When I compile my extension, webpack shows me the following error:

```
warn - Your `content` configuration includes a pattern which looks like it's accidentally matching all of `node_modules` and can cause serious performance issues.
warn - Pattern: `./**/*.tsx`
warn - See our documentation for recommendations:
warn - https://tailwindcss.com/docs/content-configuration#pattern-recommendations
✖︎✖︎✖︎ test-extension compiled with errors in 2703 ms.
WARNING in ./node_modules/libsodium-sumo/dist/modules-sumo/libsodium-sumo.js 1:568502-568519
Module not found: Error: Can't resolve 'crypto' in '/Users/aeddi/Code/test-extension/node_modules/libsodium-sumo/dist/modules-sumo'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }	
```

I dug a bit and I see that the project is indeed using version 5 of webpack. While looking for a solution, I saw that some people suggested modifying the `tsconfig.json` to add the following parameter:

```js
"compilerOptions": {
  "paths": {
    "crypto": [
      "./node_modules/crypto-browserify"
    ]
  }
}
```

But it doesn't work. Il looks like my only option is to modify the webpack config, but I can’t figure out how to do that. 
Does anyone have a solution?

**Comment by cezaraugusto** [comment]
hi @aeddi thanks for the kind words.

I made a template using Node.js polyfills, please try

```sh
npx extension@latest create my-extension --template=new-crypto
```

Code is in https://github.com/extension-js/extension.js/tree/main/examples/new-crypto.

<img width="1200" alt="Screenshot 2024-09-13 at 23 04 34" src="https://github.com/user-attachments/assets/422e15fb-0b4a-4668-96e0-89a073fd1dcb">

**Comment by aeddi** [comment]
Thanks for your quick response! It works, problem solved on my end! 👍
