### ISSUE TITLE
Replacing `background.service_worker` with `background.scripts` when building for Firefox

### ISSUE THREAD

**Issue by wottpal** [extension-js/extension.js#189]
Unfortunately, [Firefox does still not fully support Manifest v3](https://stackoverflow.com/a/75203925) at this point.

![CleanShot 2024-09-16 at 14 10 16@2x](https://github.com/user-attachments/assets/c30de30f-4a18-4d72-95aa-0a9fdaf61461)

One thing that needs to be changed after building for Firefox via `extension build -b firefox` when using background scripts is this (rename & put in array):

```json
---  "background": {
---    "service_worker": "background/service_worker.js"
---  },

+++ "background": {
+++ "scripts": ["background/service_worker.js"]
+++ },
```

**(Automated) Workaround with [jq](https://jqlang.github.io/jq/):**

```jsonc
"scripts": {
    "build:firefox": "extension build -b firefox && (cd dist/firefox && jq '.background.scripts = [.background.service_worker] | del(.background.service_worker)' manifest.json > tmp.json && mv tmp.json manifest.json)",
  // …
```

**Comment by cezaraugusto** [comment]
you can use the browser prefix for the field you want to target.

```json
{
  "background": {
    "chromium:service_worker": "background/service_worker.js",
    "firefox:scripts": ["background/service_worker.js"]
  }  
}
```

does it work for your case?

**Comment by cezaraugusto** [comment]
ping @wottpal

**Comment by wottpal** [comment]
Nice, I didn't know about those browser-specific selectors. I gave it a try but there is still an issue with this solution.

`manifest.json`

```json
  "background": {
    "chromium:service_worker": "src/action/background.ts",
    "firefox:scripts": ["src/action/background.ts"]
  },
```

`dist/firefox/manifest.json`

```json
  "background": {
    "scripts": [
      "background/scripts.js"
    ]
  },
```

… Buuut `background/scripts.js` does not exist in the firefox bundle, the file is still named (as it should probably): `service_worker.js`.

**Comment by cezaraugusto** [comment]
fixed today. please try the latest version and let me know how it goes!

**Comment by cezaraugusto** [comment]
@OSpoon could you pls confirm fix works as well?

**Comment by wottpal** [comment]
Yes, seems to be fixed on my end. Though, since updating to `beta.1` environment variables stopped working for me in this very service worker. Might this be related and/or should i open a new issue?

![CleanShot 2024-09-23 at 13 54 49@2x](https://github.com/user-attachments/assets/4ec4f757-af68-4fe6-8b39-4b5301d40f16)

**Comment by cezaraugusto** [comment]
@wottpal I updated the content-env template to include a variable in the background and it seems to work ok. could you give it a go?

```sh
pnpx extension@latest create my-extension-env --template=content-env
my-extension-env
pnpm dev
```

**Comment by wottpal** [comment]
After an extensive debugging session comparing the template with my project, it turned out to be the `EXTENSION_PUBLIC_` prefix which needs to be prepended to the variable. 🙈 Now working.

When is this necessary and when not? I'm using the variable in my background script only. Might make sense to add this to the docs (or at least I've overseen it).

**Comment by cezaraugusto** [comment]
@wottpal tThe `PUBLIC_` prefix is a guard to ensure users really want to expose the env var to the browser. sometimes people use Extension.js along with Next.js for example, which runs variables that should not be exposed outside the server, so the prefix is a way to support only what you want to be publicly visible

**Comment by wottpal** [comment]
Makes sense! Still would suggest adding it to the docs [here](https://extension.js.org/docs/guides/development/environment-variables) :)
