### ISSUE TITLE
Lockfiles shouldn't be added to .gitignore by default

### ISSUE THREAD

**Issue by arvindpunk** [extension-js/extension.js#206]
https://github.com/extension-js/extension.js/blob/09ac34e3d8f905528e835fca4758b7285439e501/programs/create/steps/write-gitignore.ts#L24

`package-lock.json` (and `yarn.lock`) shouldn't be part of .gitignore - they are expected to be committed into source control.

refs: 
- https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json
- https://classic.yarnpkg.com/lang/en/docs/yarn-lock/#toc-check-into-source-control

**Comment by cezaraugusto** [comment]
I agree. could you send a PR to update it? I'm happy to approve

**Comment by akadotsh** [comment]
Hi @cezaraugusto, I have raised a PR to fix the issue.

**Comment by arvindpunk** [comment]
Thanks for taking this up @akadotsh 

---
related: @cezaraugusto what about `extension-env.d.ts`?

https://github.com/extension-js/extension.js/blob/f257dd5ba4da7bb6ce5e1a6b7c9afa6adabf3518/programs/create/steps/write-gitignore.ts#L24

I'm unsure if this has to be removed from .gitignore as well or not.

**Comment by cezaraugusto** [comment]
@arvindpunk we want to keep it in there. it's a required file for TypeScript project we auto-generate for every run, so if the user removes it we'll eventually rewrite, so no need to persist it.
