### ISSUE TITLE
Can't find the browser path even providing the full path

### ISSUE THREAD

**Issue by quazar-omega** [extension-js/extension.js#209]
I ran this command:
```sh
bun run dev --gecko-binary $(which firefox)
```

and I get this as output:
```
$ extension dev --gecko-binary /usr/bin/firefox

 🧩 Extension.js 2.0.0-beta.1
    Extension Name         Default Extension
    Extension Version      1.0
    Extension ID           default-extension@extension-js

►►► Default Extension compiled successfully in 926 ms.
ERROR in Firefox ✖︎✖︎✖︎ Can't find the browser path

Either install the missing browser or choose a different one via --browser flag.
NOT FOUND npm exec fx-runner
error: script "dev" exited with code 1
```

It says it can't find my browser, but the launch script for firefox is working correctly as far as I can tell:
```
$(which firefox) --version
Mozilla Firefox 130.0.1
```

What should I do here?

Other contextual information:
 - using bun instead of npm
 - running inside a devbox shell (nix)

**Comment by cezaraugusto** [comment]
@quazar-omega thanks for reporting! on it

**Comment by quazar-omega** [comment]
Thank you for looking into this, let me know if you need more troubleshooting info! :)

**Comment by cezaraugusto** [comment]
hey @quazar-omega we're at `2.0.0-beta.7`, I did a few fixes in the browser plugin. could you give it another go?

**Comment by cezaraugusto** [comment]
closing as fixed. please re-open if I'm mistaken!

**Comment by quazar-omega** [comment]
Hi! Sorry, I haven't been checking in, I'll try that again when I have time and let you know.  
In the meantime, happy holidays to you!
