### ISSUE TITLE
Docs: convert_to_link is not converting some links.

### ISSUE THREAD

**Issue by therohitdas** [extension-js/extension.js#212]
There is an issue with the documentation, the links are not built properly.
![image](https://github.com/user-attachments/assets/3c57e2f4-0b6a-4d6b-bd7f-c4c948fe88f1)

**Comment by cezaraugusto** [comment]
hey @therohitdas thanks for pointing out.
I just did a massive update to the docs so I believe this one is fixed. if you see something else wrong, please report!
