### ISSUE TITLE
wasm extension with content script fails to start on some pages

### ISSUE THREAD

**Issue by anvlkv** [extension-js/extension.js#223]
I'm building [this extension](https://github.com/anvlkv/ya-ya), following the wasm example. 

I observe that on some pages (github, mdn, perhaps more) my extension fails to start with the only error

```
Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): 
    at content-0.js:7141:34
```

I thought it may have to do with page already using something in wasm. But I don't see any wasm files loaded.

**Comment by cezaraugusto** [comment]
thanks for reporting @anvlkv.

could you create a branch with the WASM file already compiled so I can take a look? that would help a lot

**Comment by anvlkv** [comment]
Hi!

Sure, [here's a release](https://github.com/anvlkv/ya-ya/releases/tag/test-ready)

I haven't tried other browsers than chrome yet, but chrome shows the issue.

**Comment by cezaraugusto** [comment]
@anvlkv to fix the issue you can try the approach mentioned [in this discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/JYs5MrWhGA8). also see [this discussion](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/sJiaTnFMLHQ) where a user reports a similiar issue + solution

**Comment by cezaraugusto** [comment]
@anvlkv closing as not actionable, please re-open if I'm mistaken. thanks!
