### ISSUE TITLE
Is It Possible to Access Environment Variables in Background Script?

### ISSUE THREAD

**Issue by bytrangle** [extension-js/extension.js#225]
[This article](https://extension.js.org/docs/features/environment-variables) includes examples for using environment variables in manifest, locale json files, html files and jsx components, but no example for background script.
For example, given an environment variable `ID` in `.env` file, I've tried to access both $ID and `process.env.ID` but both gave errors.

**Comment by bytrangle** [comment]
Thanks. EXTENSION_PUBLIC works. So any env without EXTENSION_PUBLIC can't be accessed? Can you give an example on how to use private envs when they can't be accessed?

**Comment by cezaraugusto** [comment]
yes, any variable without `EXTENSION_PUBLIC` will not work. in the next release, `EXTENSION_` (without `PUBLIC_`) will also work.

the goal of requiring a prefix for environment variables is to ensure users know that they are as public as any browser extension output code, so not the best way to store secure data. if you really need to use private variables inside an extension, consider making an API where you can securely fetch the data you want

**Comment by bytrangle** [comment]
API is what I've been considering. Thanks for the clarification.
