### ISSUE TITLE
Support for template composition

### ISSUE THREAD

**Issue by hhimanshu** [extension-js/extension.js#47]
Hey, I found your project to be useful. I was wondering if there is a way to say template="tailwind" && template="content"

**Comment by cezaraugusto** [comment]
Not possible, but that's a great idea!

Steps to get it done:

1) Have a new "content-tailwind" template within the [templates folder](https://github.com/cezaraugusto/extension.js/tree/main/programs/create/templates). There is a [react-typescript](https://github.com/cezaraugusto/extension.js/tree/main/programs/create/templates/react-typescript) template at the moment that can be used as a reference, as it uses a content_script file with Tailwind.css.

<img src="https://extension.js.org/n/getting-started/templates/dfbe8024154a88a1a1e97560b3144dbf01ba9346.png">

> The react-typescript template

2) in the `--template` [flag argument](https://github.com/cezaraugusto/extension.js/blob/main/programs/cli/cli.ts#L125), replace any `,` input value with `-`, and sort alphabetically. This will make `--template=tailwind,content` into `content-tailwind`. If step 1) is done, it should call the template just fine.

I'm currently focused on adding more browser and framework support, but would be great to see this in the future. Will set this as open for grabs :)

**Comment by cezaraugusto** [comment]
@OSpoon is this something you would be interested to implement?

**Comment by OSpoon** [comment]
> @OSpoon is this something you would be interested to implement? 这是你有兴趣实现的吗？

I am interested，I will try to implement this feature in my free time.

**Comment by cezaraugusto** [comment]
@hhimanshu @OSpoon after a very deep thought I decided not to move forward with this one as it's very unlikely that we'll be able to provide good support for this feature given other priorities. Closing as not actionable, but really appreciate the efforts to make this possible
