### ISSUE TITLE
Add option to initialize git along with the project

### ISSUE THREAD

**Issue by jmg-duarte** [extension-js/extension.js#54]
As the title says. 

I'm happy to help with a bit of guidance. Just let me know more or less where the feature relevant code lives!

**Comment by cezaraugusto** [comment]
Hi @jmg-duarte, do you mean running `git init` for new projects? Could you describe more fully?

**Comment by cezaraugusto** [comment]
BTW for editing parts of creating new extensions, you can follow the `create` module index ([here]`https://github.com/cezaraugusto/extension.js/blob/main/programs/create/module.ts)). I wrote a guide in [`CONTRIBUTING.md`](https://github.com/cezaraugusto/extension.js/blob/main/CONTRIBUTING.md) that should help on with the setup, but feel free to ping if you need help a hand on that.

**Comment by jmg-duarte** [comment]
> Hi @jmg-duarte, do you mean running `git init` for new projects? Could you describe more fully?

Yes! And adding a `.gitignore`

**Comment by cezaraugusto** [comment]
@jmg-duarte happy to share that this is the default in extension@1.8.0 ✨

Thanks for the suggestion and let me know if there's something else!
