### ISSUE TITLE
Setting the execution environment for content script to `MAIN` throws an error

### ISSUE THREAD

**Issue by nimeshnayaju** [extension-js/extension.js#66]
When the execution world for a content script is set to `MAIN`, I notice the following error:

```
Uncaught Error: No chrome or browser runtime found
    at get runtime (publicPath:3:1)
    at publicPath:5:1
    at publicPath:5:1
    at startup:8:1
```

Invocation: `publicPath:3`

```js
var runtime = isBrowser ? browser : isChrome ? chrome : (typeof self === 'object' && self.addEventListener) ? { get runtime() { throw new Error("No chrome or browser runtime found") } } : { runtime: { getURL: x => x } }
```

This is my manifest configuration:

```json
{
  "content_scripts": [
    {
      "matches": ["*://localhost/*"],
      "js": ["./content.ts"],
      "world": "MAIN"
    }
  ],
}
```

I am guessing because `chrome.runtime` is called internally by `extension.js` inside the content script which doesn't support the extension APIs any longer since the content script executes in the page content when world is set to `MAIN`.

Link to content script configuration documentation: https://developer.chrome.com/docs/extensions/reference/manifest/content-scripts

**Comment by cezaraugusto** [comment]
Hi @nimeshnayaju thanks a lot for reporting! I created an issue in the external dependency that the bug points to, so hopefully they can help figuring out a good way to solve it.

**Comment by cezaraugusto** [comment]
@nimeshnayaju this took a while, but happy to share it's finally fixed!

Pls ensure you are running v1.8.0 and let me know if the bug persists. Happy to assist!

**Comment by cezaraugusto** [comment]
@nimeshnayaju this is very cool, happy to know that!

Are you OK if I reference Lexical DevTools in a future showcase page for Extension.js?

**Comment by nimeshnayaju** [comment]
@cezaraugusto Of course! I really enjoyed using Extension.js. Loved that I mostly had to worry about the core logic of the application and rest was handled very well by Extension.js. Thank you!
