### ISSUE TITLE
Mainfest file have issue on icons path

### ISSUE THREAD

**Issue by Ajayghoshm** [extension-js/extension.js#87]
![image (1)](https://github.com/cezaraugusto/extension.js/assets/29367198/4f8f698f-b958-4fa0-943a-ee2630ebb3d2)
![image (2)](https://github.com/cezaraugusto/extension.js/assets/29367198/1ccf72b1-8d44-4a86-af1a-347b27f6612f)

these are the actual file and the file being generated, the path of the icons is incorrect, issue is happening in windows system

**Comment by cezaraugusto** [comment]
Hi @Ajayghoshm thanks for reporting!

I'm not sure what the issue is, could you describe it more fully?

**Comment by cezaraugusto** [comment]
I see. Files within public/ should resolve to public/ always. ManifestPlugin should handle that, so that's a bug.

**Comment by hitwill** [comment]
This problem still exists with version: `^2.0.0-alpha.5`

**Comment by cezaraugusto** [comment]
cc @OSpoon is it broken on your end as well?

**Comment by OSpoon** [comment]
cc @cezaraugusto  @hitwill 
I tested two templates in a Windows environment, and I did not find any issues with missing images. I think the directory files meet the expected criteria. If there are any issues, please provide more information.

```bash
npx extension@latest create react-ext --template=content-react
```

```bash
npx extension@latest create react-ext --template=new-react
```

**Comment by hitwill** [comment]
Tested on an existing project that was upgraded to: ` "extension": "^2.0.0-alpha.8",`

The `manifest.json` has the following setting:
```json
"icons": {
    "16": "public/icon/icon_16.png",
    "32": "public/icon/icon_32.png",
    "48": "public/icon/icon_48.png",
    "128": "public/icon/icon_128.png"
  }
```

running `dev` generates the following error:


<img width="268" alt="image" src="https://github.com/user-attachments/assets/3992503d-f80b-47bf-9e5d-2ea7b318e7a1">

The generated manifest file has the following setting:

```json
 "icons": {
    "16": "icons/icon_16.png",
    "32": "icons/icon_32.png",
    "48": "icons/icon_48.png",
    "128": "icons/icon_128.png"
  },
```

Note that the path says `icons/` instead of `public/`

**Comment by hitwill** [comment]
I think the problem is with upgrading an existing project. To fix this:
1. create an `images` directory and store the icons there
2. update the manifest file to:
```json
  "icons": {
    "16": "images/icon/icon_16.png",
    "32": "images/icon/icon_32.png",
    "48": "images/icon/icon_48.png",
    "128": "images/icon/icon_128.png"
  }

```

This resolved the issue for me

**Comment by cezaraugusto** [comment]
@hitwill thanks, I did a regression during the current v2 updates. I just pushed a PR to fix the issue
