### ISSUE TITLE
After running the build command, both the images and styles are missing.

### ISSUE THREAD

**Issue by OSpoon** [extension-js/extension.js#96]
## Description：

After running the build command, both the images and styles are missing.

## Steps：

1. Create an extension project based on the `vue-typescript` template.
2. Run `npm run build`.
3. Load the `dist/chrome` folder in Chrome browser developer mode.

## Preview：

<img width="1439" alt="image" src="https://github.com/cezaraugusto/extension.js/assets/10126623/ca958314-6cd6-496e-850a-6494673e3d75">

@cezaraugusto ，I feel very sorry.

**Comment by cezaraugusto** [comment]
Reproduced. Working on a fix
